package org.rapidpm.vaadin.jumpstart.gui.design.analytics.github.organizations;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GithubOrganizationsScreen extends VerticalLayout {
    protected Button btnLoad;
    protected Button btnClear;
    protected Panel panelChart;

    public GithubOrganizationsScreen() {
        Design.read(this);
    }
}
