CREATE TABLE PUBLIC.LOGIN (
  ID          INTEGER      NOT NULL PRIMARY KEY,
  USERNAME    VARCHAR(256) NOT NULL,
  PASSWORD    VARCHAR(256) NOT NULL,
  VALID       BOOLEAN      NOT NULL,
  CUSTOMER_ID INTEGER      NOT NULL

);
